name: Metrics
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          user: abhirajsinha
          filename: metrics.svg
          base: header, activity, community
          config_timezone: Asia/Kolkata
          config_octicon: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_calendar: yes
          plugin_calendar_limit: 0
